import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '../Data/Yugioh.json'
import { useState } from 'react'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const [burger, setBurger] = useState("burger-bar unclicked")
  const [menu, setMenu] = useState("menu hidden")
  const [Clicked, setClicked] = useState(false)

 
  const updateMenu = () => {
      if(!Clicked) {
          setBurger("burger-bar clicked")
          setMenu("menu visible")
      }
      else {
          setBurger("burger-bar unclicked")
          setMenu("menu hidden")
      }
      setClicked(!Clicked)
  }

  console.log(record);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
            <nav>
                <div className="burger-menu" onClick={updateMenu}>
                    <div className={burger} ></div>
                    <div className={burger} ></div>
                    <div className={burger} ></div>
                </div>
                
            </nav>

            <div className={menu}>
            <a href="/">Home</a>
            <a href="/info">Info</a>
            </div>
        </div>
      <main className={styles.main} id="PageColour">
       

        <><h1>Yu-gi-oh Api</h1>
          {
            record.map ((rec, index) => {
              return (
                <div key={index}>
                  
                  <div >{rec.id}</div>
                  <div className={styles.Titles}>{rec.Name}</div>
                  <div className={styles.spacer}>
                  <Image src={rec.src} width={220} height={220} margin-top={-10}/>
                  </div>
                  <div className={styles.Cards}>
                    <div className={styles.cardspace1}>
                      <div className={styles.type}> {rec.Type}</div>
                      <div className={styles.cardinfo}>{rec.Info}</div>
                 <div className={styles.stats}> 
                 {rec.ATK}
                  {rec.DEF}
                  </div> 
                  </div>
                  </div>
                </div>
              )
            })
          }
          
        </>
      </main>
    </>
  )
}

