import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '../data/Yugioh.json'
import Cards from '@/comps/cards'
import styled from 'styled-components'
const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  console.log(record);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
          {
            record.map ((rec, index) => {
              return (
                <div key={index}>
                  <div >{rec.id}</div>
                  <div className={styles.Titles}>{rec.Name}</div>
                  <div className={styles.spacer}></div>
                  <Image src={rec.src} width={220} height={220}/>
                  
                  <div className={styles.Cards}>
                    <div className={styles.cardspace1}> {rec.Type}</div>
                 <div  className={styles.stats}> {rec.ATK}/
                  {rec.DEF}
                  </div> 
                  </div>
                </div>
              )
            })
          }

        </>
      </main>
    </>
  )
}

