import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '../data/Yugioh.json'

import { useState } from 'react'
import React from 'react'
import Cards from '@/comps/cards'
import styled from 'styled-components'
const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const [burger_class, setBurgerClass] = useState("burger-bar unclicked")
  const [menu_class, setMenuClass] = useState("menu hidden")
  const [isMenuClicked, setIsMenuClicked] = useState(false)

  // toggle burger menu change
  const updateMenu = () => {
      if(!isMenuClicked) {
          setBurgerClass("burger-bar clicked")
          setMenuClass("menu visible")
      }
      else {
          setBurgerClass("burger-bar unclicked")
          setMenuClass("menu hidden")
      }
      setIsMenuClicked(!isMenuClicked)
  }

  console.log(record);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} id="PageColour">
       
        <div >
            <nav>
                <div className="burger-menu" onClick={updateMenu}>
                    <div className={burger_class} ></div>
                    <div className={burger_class} ></div>
                    <div className={burger_class} ></div>
                </div>
                
            </nav>

            <div className={menu_class}>
            <a href="/">Home</a>
            <a href="/Info">Info</a>
            </div>
        </div>
        <><h1>Yu-gi-oh Api</h1>
          {
            record.map ((rec, index) => {
              return (
                <div key={index}>
                  
                  <div >{rec.id}</div>
                  <div className={styles.Titles}>{rec.Name}</div>
                  <div className={styles.spacer}>
                  <Image src={rec.src} width={220} height={220} margin-top={-10}/>
                  </div>
                  <div className={styles.Cards}>
                    <div className={styles.cardspace1}>
                      <div className={styles.type}> {rec.Type}</div>
                      <div className={styles.cardinfo}>{rec.Info}</div>
                 <div className={styles.stats}> 
                 {rec.ATK}
                  {rec.DEF}
                  </div> 
                  </div>
                  </div>
                </div>
              )
            })
          }
          
        </>
      </main>
    </>
  )
}

